name: NestJS CI
on: ["push"]
jobs:
  build:
    env:
      DATABASE_USERNAME: "basicfit"
      DATABASE_PASSWORD: "basicfit"
      DATABASE_DATABASE: "basicfit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
  services:
    postgres:
      image: postgres:15
      env:
        POSTGRES_USER: basicfit
        POSTGRES_PASSWORD: basicfit
        POSTGRES_DB: basicfit
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        - 5432:5432
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test